### ISSUE TITLE
Exception: Missing hash key: <hash_goes_here> (KeyError)

### ISSUE THREAD

**Issue by drhuffman12** [jasonl99/calculator#1]
When I try to browse to the same calculator URL (e.g.: http://localhost:3000/foos) from two browser sessions, I get an error like below in the second browser:

```
[development] Kemal is ready to lead at http://0.0.0.0:3000

2017-02-14 19:52:36 -0500 200 GET /foos 205.1µs
2017-02-14 19:52:36 -0500 304 GET /css/style.css 53.5µs
2017-02-14 19:52:36 -0500 200 GET /js/app.js 64.9µs
Exception: Missing hash key: 977288949394560 (KeyError)
0x4ae09e: ??? at /home/drhuffman/.cache/crystal/macro81093616.cr 10:28
0x521341: ??? at /opt/crystal/src/hash.cr 124:9
0x4d8040: ??? at /home/drhuffman/_dev_/github.com/jasonl99/calculator/lib/kemal/src/kemal/context.cr 12:7
0x55e157: ??? at /home/drhuffman/_dev_/github.com/jasonl99/calculator/lib/kemal/src/kemal/route_handler.cr 17:7
0x551f06: ??? at /opt/crystal/src/http/server/handler.cr 24:7
0x550757: ??? at /home/drhuffman/_dev_/github.com/jasonl99/calculator/lib/kemal/src/kemal/websocket_handler.cr 11:7
0x54d651: ??? at /home/drhuffman/_dev_/github.com/jasonl99/calculator/lib/kemal/src/kemal/static_file_handler.cr 50:18
0x5599ee: ??? at /opt/crystal/src/http/server/handler.cr 24:7
0x557a94: ??? at /opt/crystal/src/http/server/handler.cr 24:7
0x55d7e5: ??? at /opt/crystal/src/http/server/handler.cr 24:7
0x53e47d: ??? at /home/drhuffman/_dev_/github.com/jasonl99/calculator/lib/kemal/src/kemal/init_handler.cr 11:7
0x416c38: ??? at /opt/crystal/src/fiber.cr 114:3
0x0: ??? at ??

```

The steps I took were basically:

* Clone (https:..., not git:...) the `lattice-core` and `calculator` repos under the same local parent folder
* Adjust calculator's `shard.yml` to point to my local `lattice-core`:
```
...
  lattice-core:
    path: ../lattice-core
...
```
* `shards install`
* `crystal build --release src/calculator.cr`
* `./calculator`
* Browse to http://localhost:3000/foos from two browsers
* I also tried: `rm -rf ~/.cache/crystal` and rebuild/re-run

This is using commits:

- https://github.com/jasonl99/lattice-core/commit/693f022da904d73ddd13860c6be10bf3f5c952ec
- https://github.com/jasonl99/calculator/commit/b7b4116dc0e75caade16964337297c98b3c5fae6

.. and versions:

```
$ shards --version
Shards 0.7.1 (2017-01-20)

$ crystal --version
Crystal 0.20.5 [ccf46c0] (2017-01-20)
```

**Comment by drhuffman12** [comment]
I get the same kind of error if I adjust my `shards.yml` file to:

```
...
  lattice-core:
    github: jasonl99/lattice-core
...
```

**Comment by jasonl99** [comment]
Yes, I have an update for parts of this, but I'm struggling a bit with something that only happens when doing a build --release.  The code for that's not up there yet, but I think you'll find it better once it's up later tonight

**Comment by drhuffman12** [comment]
This issue seems fixed; at least when running with:

```sh
$ crystal --version
Crystal 0.23.1 [e2a1389] (2017-07-13) LLVM 3.8.1

$ shards --version
Shards 0.7.1 (2017-07-13)
```
